- src/pages/login/index.js
- src/pages/login/style.module.css
added a modal instead of a separate page for the resetting of password
> feat: account recovery

- src/pages/login/index.js
Login button is disabled unless the fields are filled out.
> feat: login

- src/App.js
does not work as intended, just navigate to login, no modal msg--can't afk for an hour lol
> added temporary navigation for session expiry

- src/App.js
- src/common/drawer/index.js
- src/common/drawer/style.module.css
- src/pages/admin dashboard/index.js
- src/pages/dashboard/index.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/index.js
- src/pages/employee dashboard/style.module.css
- src/pages/registration/index.js
- src/pages/settings/Password.jsx
- src/pages/settings/index.js
Form feedback was not showing up when registering unless the Register button was clicked. 
- - - -
A current password field was added for enhanced security measures. If the password entered for the current password is incorrect, an error will show up. 
- - - -
Submit button is now disabled when fields are not filled (not including Proof)
Users are also now unable to input future dates. 
When adding a new record:
When editing a record:
Date shows up properly on the form when editing.
- - - - 
The drawer is no longer a "minimized" version with an arrow at the left of the screen. It is now a hamburger button at the top left of the screen.
Moved the following tabs to the top right of the navigation bar but still accessible through the drawer.
- Notifications
- Settings
- Log out
- - - -
- …
> fix: registration, security mgmt, drawer/navbar

- src/App.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/index.js
- src/pages/employee dashboard/style.module.css
- src/pages/registration/index.js
- src/pages/settings/index.js
- src/styles/App.module.css
im too tired to add screenshots
just test it bc i did thanks
> fix: registration, login, swtd

- src/pages/settings/Password.jsx
changed password variables in api call
> fix: security mgmt

- src/api/comments.js
- src/common/modals/CommentModal.js
- src/common/modals/style.module.css
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/style.module.css
In the SWTD Details page, there's a comments card underneath the Details card. It shows "No comments yet." when there are no comments added.
When a comment is added, it shows the author of comment, message, date & time, edit icon, and delete icon.
When you press the edit icon, it shows a modal for editing a comment. After pressing save, it shows a modal to confirm changes.
There's an indicator for an edited comment.
When deleting a comment, there's a confirmation modal that confirms the deletion of the comment.
> feature: comments

- src/api/swtd.js
- src/common/modals/EditCommentModal.js
- src/common/modals/EditProofModal.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/index.js
- src/pages/employee dashboard/style.module.css
partial merge for dashboard rendering - has fixed add swtd
> feat: swtd validation

- src/api/swtd.js
- src/common/modals/EditProofModal.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/index.js
Description is also for the previous [pull request](https://github.com/ArchonsDev/react-pointwatch-web/pull/27).
Button is now disabled when user does not upload proof. The field also includes the files it accepts.
Form control does not accept any other file aside from the required file types mentioned (PDF, PNG, JPEG/JPG)
This page no longer has the "upload" field from the previous design. It turned into "View" and "Change Proof"
- View Button is for viewing the uploaded proof
- Change Proof is for updating proof if required.
When viewing the proof, a modal pops up showing the uploaded file.
When updating the proof, it's separate from the function of the "EDIT" button. 
> Edit button is only for editing the fields/details of the SWTD, excluding the Proof
> Change Proof is changing the …
> feat: swtd proof for validation

- src/App.js
- src/api/admin.js
- src/api/user.js
- src/common/drawer/index.js
- src/common/drawer/style.module.css
- src/common/validation/points.js
- src/data/categories.json
- src/pages/admin/Term.jsx
- src/pages/dashboard/EmployeeSWTD.js
- src/pages/dashboard/ViewSWTD.js
- src/pages/dashboard/index.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/Comments.jsx
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/SWTDInfo.jsx
- src/pages/employee dashboard/index.js
- src/pages/login/index.js
- src/pages/settings/General.jsx
`Sprint 4: SWTD Validation Feature`
Branch: `feature/swtd`
This pull request includes the finishing touches for the SWTD validation where it includes the points calculation and granting/revoking of clearance for an employee. Some stuff about the dashboard are found [here](https://github.com/ArchonsDev/react-pointwatch-web/pull/30).
For the backend, I used the `feature/swtd` branch during the development of these features. Please ask @cxrvxxxx if the QA branch is updated or not. I'm also not entirely sure if this requires dropping and creating the database again but maybe do it nlang just to be safe?
- - - -
- When no term is selected, it only shows the "Point Balance" which is the excess points the user has for all terms and will be carried over to the next term. This has replaced the …
> feat: swtd validation (finished)

- src/common/format/date.js
- src/common/validation/utils.js
- src/pages/admin/Term.jsx
- src/pages/dashboard/EmployeeSWTD.js
- src/pages/dashboard/ViewSWTD.js
- src/pages/dashboard/index.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
- src/pages/employee dashboard/index.js
Made the necessary changes based on Issue #32 where:
- Dashboard does not update the point balance correctly after granting clearance for employee
- Table label is unclear  for the list of employees (Points > Point Balance)
- There was no validation check for the date when editing a SWTD
- Removed the valid date check when creating Term. Admins should be able to create a term before and after current date as it does not make sense to apply this limit for terms.
- To make it clearer, what if the admin forgot to add terms and the term has already started?
- In the View SWTD Page, the Edit and Delete buttons no longer appear when the employee has already been cleared for that term. Allowing a user to edit/delete these SWTDs (in the term where they are cleared) may cause issues with the …
> fix: rendering issues

- src/pages/dashboard/EmployeeSWTD.js
- src/pages/dashboard/index.js
- src/pages/employee dashboard/index.js
I added a search bar and a status filtering option for the following pages: 
- Employee Dashboard (List of SWTDs)
- Admin/Staff Dashboard
- List of Employees
- Employee's SWTD (Same as Employee Dashboard)
> feat: search bar, filtering options

- src/pages/login/index.js
- src/pages/login/style.module.css
- src/pages/registration/index.js
- src/pages/registration/style.module.css
- src/pages/reset password/index.js
- src/pages/reset password/style.module.css
- src/pages/settings/Password.jsx
- src/pages/settings/style.module.css
@shinwoniee @trciarnt more stuff to test 😆 i think they're functional pero tryi lang 🙂 lmk if i missed any pages bc my brain just cant anymore
~~also removed the timeout shit for login lol as requested by @cxrvxxxx~~
> style: added show/hide pw

- src/pages/admin/ClearanceActivity.jsx
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.js
> fix: added validation when selecting terms

- public/index.html
- src/api/admin.js
- src/common/format/date.js
- src/common/format/time.js
- src/pages/admin/ClearanceActivity.jsx
- src/pages/admin/Term.jsx
- src/pages/admin/ValidationActivity.jsx
- src/pages/admin/style.module.css
- src/pages/dashboard/EmployeeSWTD.js
- src/pages/dashboard/ViewSWTD.js
- src/pages/dashboard/index.js
- src/pages/employee dashboard/AddSWTD.js
- src/pages/employee dashboard/EditSWTD.jsx
- src/pages/employee dashboard/SWTDDetails.js
- src/pages/employee dashboard/index.js
- Added spinners for loading pages lol
- Change the date formats from numbers whatever to word stuff (ex. 05-22-2024 -> May 22, 2024)
- Change military time format display to 12-hr format (00:00 -> 12:00am)
- Disabled `View Proof` with the same condition for the `Edit` and `Delete` buttons
- Disabled form fields and `Submit` button after clicking
> fix: changed stuff based on final proj feedback

- src/components/Data.js
- src/components/Line.js
- src/components/ProgressBar.js
- src/components/styles.module.css
- src/data/months.json
- src/pages/employee dashboard/index.js
- src/pages/employee dashboard/style.module.css
> merge base code with emp dashboard

- src/pages/admin/HeadPromotion.jsx
- src/pages/admin/StaffPromotion.jsx
page returns blank when department is null which happens when signing in w microsoft lol
> fix: removed department sort in head/staff in system mgmt page

- src/pages/dashboard/EmployeeSWTD.js
- src/pages/dashboard/index.js
- src/pages/dashboard/style.module.css
merge head dashboard changes to wip basecode
> head dashboard changes

- src/pages/dashboard/ViewSWTD.js
loading feature when approving/rejecting & granting/revoking clearances
> merge with basecode

- src/pages/dashboard/EmployeeSWTD.js
@owembii 
disabled the buttons for clear/revoke, export in head dashboard while handling request to prevent multiple requests at once
> merge assigned task with wip basecode

- src/pages/registration/index.js
@owembii 
disable button when sending request on register page
> merge wip basecode with minor changes
